volumes:
  cache:
    driver: local #докер создаст папку cache локально
  db-data:
    driver: local

services:
  taskboard:
    depends_on:
      - postgres
      - redis
    container_name: tasklist
    build:
      context: .
    env_file:
      - .env
    ports:
      - '8080:8080'
    labels:
      org.springframework.boot.ignore: true


  postgres:
    image: 'postgres:16.3'
    container_name: postgres
    env_file:
      - .env
#    environment:
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning #--requirepass YXNkYXNkYXNkYXNk #команда запуска редиса. Указываем пароль в кодировке base64
    volumes:
      - cache:/data  #маппим папку cache, которую создаст докер в папку data контейнера