services:
  postgres:
    image: 'postgres:16.3'
    environment:
      - POSTGRES_DB=task_board
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
