spring:
  application:
    name: TaskBoard
  #берем переменные окружения из файла .env  (.properties)
  config:
    import: optional:file:.env[.properties]

  cache:
    type: redis
    cache-names: redis-cache
  #becasue we have docker support in pon.xml   we don't need to configure all objects from docker compose.
  #we dont need to configure database and redis in particular
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:liquibase/db.main-changelog.yaml
    enabled: true
    default-schema: public

  #here is some imitation of sql migration
#  sql:
#    init:
#      mode: never #using  mode "always" we will perform sql code  every app launch  sql code ( sql code from  schema.sql )
#      continue-on-error: false
#      data-locations: classpath:demo_data.sql #addition file with sql code. It put test data to sql tables. Should be perform only 1 time, that is why now it's turn off

security:
  jwt:
    access: 1
    refresh: 30
    # secret that use to make signature of the token. It's a random string that encode via Base64
    secret: ${JWT_SECRET}

springdoc:
  override-with-generic-response: false
